# Generated by Django 4.1.2 on 2022-11-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_product_secondary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
