# Generated by Django 4.1.2 on 2022-11-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
